# Generated by Django 5.2.15 on 2026-08-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_calendarevent_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='attended',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
