# Generated by Django 5.2.15 on 2026-06-09 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='airtable_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
