# Generated by Django 5.2.15 on 2026-06-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_airtable_id_to_account'),
        ('team', '0002_add_airtable_collaborator_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='member_accounts', to='team.teammember'),
        ),
    ]
