# Generated by Django 5.2.15 on 2026-07-10 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_account_admin_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountartifact',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='accountartifact',
            name='secondary_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
