# Generated by Django 5.2.15 on 2026-07-16 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_accountartifact_account_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, default='')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.account')),
            ],
            options={
                'ordering': ['position', 'name'],
            },
        ),
    ]
