# Generated by Django 5.2.15 on 2026-08-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_accountrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountproject',
            name='sf_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
