# Generated by Django 5.2.15 on 2026-08-11 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_add_project_sf_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountproject',
            name='kind',
            field=models.CharField(choices=[('project', 'Project'), ('goal', 'Goal')], default='project', max_length=20),
        ),
    ]
