# Generated by Django 5.2.15 on 2026-08-27 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_accountnote_references'),
        ('team', '0006_userprofile_gmail_watch_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accountproject',
            name='sf_project_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='accounts.accountproject')),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to='team.teammember')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('project', 'team_member')},
            },
        ),
    ]
