# Generated by Django 5.2.15 on 2026-06-08 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirtableAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airtable_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email_domain', models.CharField(blank=True, default='', max_length=255)),
                ('health_score', models.CharField(blank=True, default='', max_length=64)),
                ('next_meeting', models.DateTimeField(blank=True, null=True)),
                ('open_ticket_count', models.IntegerField(default=0)),
                ('time_budget', models.IntegerField(default=0)),
                ('total_meeting_duration', models.IntegerField(default=0)),
                ('salesforce_account_id', models.CharField(blank=True, default='', max_length=128)),
                ('last_synced', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AirtableActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airtable_id', models.CharField(max_length=64, unique=True)),
                ('task', models.CharField(max_length=512)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Complete', 'Complete'), ('Blocked', 'Blocked')], default='Open', max_length=64)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=64)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('estimated_time', models.IntegerField(default=0)),
                ('time_spent', models.IntegerField(default=0)),
                ('prep_time', models.IntegerField(default=0)),
                ('slack_thread_url', models.TextField(blank=True, default='')),
                ('salesforce_task_id', models.CharField(blank=True, default='', max_length=128)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_items', to='airtable_sync.airtableaccount')),
            ],
            options={
                'ordering': ['status', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='AirtableMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airtable_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=512)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(default=0)),
                ('expected_topics', models.TextField(blank=True, default='')),
                ('gong_notes', models.TextField(blank=True, default='')),
                ('gong_url', models.URLField(blank=True, default='')),
                ('customer_slack', models.URLField(blank=True, default='')),
                ('account_team_slack', models.URLField(blank=True, default='')),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='airtable_sync.airtableaccount')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CalendarEventAccountLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_event_uid', models.CharField(max_length=512, unique=True)),
                ('categorization', models.CharField(blank=True, default='', help_text="e.g. 'Internal Meeting', 'Admin', or empty when account-linked", max_length=64)),
                ('match_method', models.CharField(blank=True, default='', help_text='domain | title | fulltext | manual', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='airtable_sync.airtableaccount')),
            ],
        ),
    ]
