# Generated by Django 5.2.15 on 2026-06-15 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airtable_sync', '0002_actionitem_task_details_assignee'),
        ('scheduler', '0003_add_meeting_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='airtableactionitem',
            name='reminder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_items', to='scheduler.reminder'),
        ),
    ]
