# Generated by Django 5.2.15 on 2026-06-15 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airtable_sync', '0003_add_reminder_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='airtableaccount',
            name='segment_workspaces',
            field=models.TextField(blank=True, default=''),
        ),
    ]
