# Generated by Django 5.2.15 on 2026-06-23 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airtable_sync', '0007_actionitem_linked_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionitemdependency',
            name='blocked_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_on_deps', to='airtable_sync.airtableactionitem'),
        ),
        migrations.AlterField(
            model_name='actionitemdependency',
            name='waiting_on_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocking_deps', to='airtable_sync.airtableactionitem'),
        ),
        migrations.AlterField(
            model_name='airtableactionitem',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Done', 'Done'), ('Blocked', 'Blocked')], default='Open', max_length=64),
        ),
    ]
