# Generated by Django 5.2.15 on 2026-07-17 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airtable_sync', '0009_actionitem_timestamps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airtableactionitem',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Done', 'Done'), ('Blocked', 'Blocked'), ('Backlogged', 'Backlogged')], default='Open', max_length=64),
        ),
    ]
