# Generated by Django 5.2.15 on 2026-08-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airtable_sync', '0011_actionitemstep'),
    ]

    operations = [
        migrations.AddField(
            model_name='airtableactionitem',
            name='status_locally_modified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='actionitemstep',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
