# Generated by Django 5.2.15 on 2026-08-18 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airtable_sync', '0012_action_item_status_locally_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='airtablemeeting',
            name='zoom_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='airtablemeeting',
            name='zoom_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
