# Generated by Django 5.2.15 on 2026-08-06 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduler', '0006_calendarevent_event_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZendeskConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdomain', models.CharField(max_length=128)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zendesk_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ZendeskTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zendesk_id', models.BigIntegerField(unique=True)),
                ('subdomain', models.CharField(max_length=128)),
                ('subject', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, default='')),
                ('zendesk_status', models.CharField(blank=True, default='', max_length=32)),
                ('zendesk_priority', models.CharField(blank=True, default='', max_length=32)),
                ('requester_email', models.CharField(blank=True, default='', max_length=255)),
                ('assignee_id', models.BigIntegerField(blank=True, null=True)),
                ('ticket_created_at', models.DateTimeField(blank=True, null=True)),
                ('ticket_updated_at', models.DateTimeField(blank=True, null=True)),
                ('url', models.TextField(blank=True, default='')),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('local_action_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zendesk_tickets', to='scheduler.actionitem')),
            ],
            options={
                'ordering': ['-ticket_updated_at'],
            },
        ),
    ]
