# Generated by Django 5.2.15 on 2026-06-23 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('account', 'Account'), ('airtable_account', 'Airtable Account'), ('action_item', 'Airtable Action Item'), ('meeting', 'Airtable Meeting'), ('calendar_event', 'Calendar Event'), ('reminder', 'Reminder'), ('task', 'Task'), ('account_note', 'Account Note'), ('artifact', 'Account Artifact'), ('meeting_note', 'Meeting Note')], db_index=True, max_length=30)),
                ('resource_id', models.PositiveIntegerField(db_index=True)),
                ('resource_label', models.CharField(blank=True, max_length=500)),
                ('content', models.TextField()),
                ('references', models.JSONField(default=list, help_text='Records referenced via @# picker: [{resource_type, resource_id, label, url}]')),
                ('mentions', models.JSONField(default=list, help_text='User mentions via @ picker: [{user_id, username, display_name}]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comments.comment')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['resource_type', 'resource_id'], name='comments_co_resourc_fbfa72_idx')],
            },
        ),
    ]
