# Generated by Django 5.2.15 on 2026-08-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='resource_type',
            field=models.CharField(choices=[('account', 'Account'), ('airtable_account', 'Airtable Account'), ('action_item', 'Airtable Action Item'), ('action_item_step', 'Action Item Step'), ('meeting', 'Airtable Meeting'), ('calendar_event', 'Calendar Event'), ('reminder', 'Reminder'), ('task', 'Task'), ('account_note', 'Account Note'), ('artifact', 'Account Artifact'), ('meeting_note', 'Meeting Note'), ('claude_skill', 'Claude Skill')], db_index=True, max_length=30),
        ),
    ]
