# Generated by Django 5.2.15 on 2026-06-12 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_add_claude_skill'),
        # Must copy data to skills app before the source table is dropped
        ('skills', '0002_copy_from_agents'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClaudeSkill',
        ),
    ]
