# Generated by Django 5.2.15 on 2026-06-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='airtable_member_id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='airtable_collaborator_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Airtable collaborator user ID (usrXXX) — used to populate Assignee / Team Members linked fields.', max_length=64),
        ),
    ]
