# Generated by Django 5.2.15 on 2026-06-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_add_airtable_collaborator_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notify_default_in_app',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_default_push',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_default_slack',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_default_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='push_subscription',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
