# Generated by Django 5.2.15 on 2026-08-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_add_staff_view_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='calendar_colors',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
