# Generated by Django 5.2.15 on 2026-06-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_add_provider_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthcredential',
            name='provider',
            field=models.CharField(choices=[('google', 'Google'), ('slack', 'Slack'), ('airtable', 'Airtable'), ('salesforce', 'Salesforce'), ('gong', 'Gong'), ('zoom', 'Zoom'), ('lucidchart', 'Lucidchart'), ('github', 'GitHub'), ('google_drive', 'Google Drive / Docs / Sheets'), ('notion', 'Notion'), ('microsoft', 'Microsoft Teams')], max_length=30),
        ),
    ]
