# Generated by Django 5.2.15 on 2026-08-06 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduler', '0006_calendarevent_event_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JiraConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud_id', models.CharField(max_length=64)),
                ('cloud_name', models.CharField(blank=True, default='', max_length=255)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jira_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JiraTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jira_key', models.CharField(max_length=64, unique=True)),
                ('cloud_id', models.CharField(max_length=64)),
                ('issue_id', models.CharField(blank=True, default='', max_length=64)),
                ('summary', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, default='')),
                ('issue_type', models.CharField(blank=True, default='', max_length=64)),
                ('jira_status', models.CharField(blank=True, default='', max_length=64)),
                ('jira_priority', models.CharField(blank=True, default='', max_length=64)),
                ('assignee_email', models.CharField(blank=True, default='', max_length=255)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('url', models.TextField(blank=True, default='')),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('local_action_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jira_tickets', to='scheduler.actionitem')),
            ],
            options={
                'ordering': ['-last_synced'],
            },
        ),
    ]
