# Generated by Django 5.2.15 on 2026-08-06 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0013_accountproject_linked_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfluenceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud_id', models.CharField(max_length=64)),
                ('cloud_name', models.CharField(blank=True, default='', max_length=255)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confluence_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConfluencePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(max_length=64, unique=True)),
                ('cloud_id', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=512)),
                ('space_key', models.CharField(blank=True, default='', max_length=64)),
                ('space_name', models.CharField(blank=True, default='', max_length=255)),
                ('url', models.TextField(blank=True, default='')),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('local_artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confluence_pages', to='accounts.accountartifact')),
                ('local_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confluence_pages', to='accounts.accountnote')),
            ],
            options={
                'ordering': ['-last_modified'],
            },
        ),
    ]
