# Generated by Django 5.2.15 on 2026-06-12 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaudeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(help_text='Shown to Claude as the tool description.')),
                ('code', models.TextField(help_text='Python async def source of the tool function.')),
                ('input_schema', models.JSONField(blank=True, default=dict, help_text="JSON Schema for the tool's input parameters.")),
                ('source_file', models.CharField(blank=True, default='', help_text='Original filename if imported from the skills/ directory.', max_length=255)),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('reviewing', 'Reviewing'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disabled', 'Disabled')], default='pending_review', max_length=20)),
                ('review_feedback', models.TextField(blank=True)),
                ('review_suggestions', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('invocation_count', models.PositiveIntegerField(default=0)),
                ('last_invoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Claude Skill',
                'verbose_name_plural': 'Claude Skills',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillInvocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.PositiveIntegerField(blank=True, help_text='ID of the AgentSession that triggered this invocation.', null=True)),
                ('arguments', models.JSONField(default=dict)),
                ('result', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error')], default='success', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('invoked_at', models.DateTimeField(auto_now_add=True)),
                ('invoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_invocations', to=settings.AUTH_USER_MODEL)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invocations', to='skills.claudeskill')),
            ],
            options={
                'verbose_name': 'Skill Invocation',
                'verbose_name_plural': 'Skill Invocations',
                'ordering': ['-invoked_at'],
            },
        ),
    ]
