# Generated by Django 5.2.15 on 2026-06-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_copy_from_agents'),
    ]

    operations = [
        migrations.AddField(
            model_name='claudeskill',
            name='command',
            field=models.CharField(blank=True, default='', help_text='Slash command shortcut, e.g. /generate_status_report.', max_length=64),
        ),
    ]
