# Generated by Django 5.2.15 on 2026-07-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0006_agentskill_pins'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillinvocation',
            name='input_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skillinvocation',
            name='output_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
