# Generated by Django 5.2.15 on 2026-06-08 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesforceAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sf_id', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True, default='')),
                ('industry', models.CharField(blank=True, default='', max_length=128)),
                ('account_type', models.CharField(blank=True, default='', max_length=64)),
                ('phone', models.CharField(blank=True, default='', max_length=64)),
                ('billing_city', models.CharField(blank=True, default='', max_length=128)),
                ('billing_country', models.CharField(blank=True, default='', max_length=128)),
                ('owner_sf_id', models.CharField(blank=True, default='', max_length=32)),
                ('owner_name', models.CharField(blank=True, default='', max_length=255)),
                ('last_synced', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SalesforceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_url', models.URLField()),
                ('namespace', models.CharField(blank=True, default='cc4sf', help_text='Cloud Coach package namespace, auto-discovered on connect.', max_length=32)),
                ('sf_user_id', models.CharField(blank=True, default='', max_length=64)),
                ('sf_user_email', models.CharField(blank=True, default='', max_length=255)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sf_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalesforceProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sf_id', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=512)),
                ('status', models.CharField(blank=True, default='', max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('owner_sf_id', models.CharField(blank=True, default='', max_length=32)),
                ('owner_name', models.CharField(blank=True, default='', max_length=255)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='salesforce_sync.salesforceaccount')),
            ],
            options={
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SalesforceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sf_id', models.CharField(max_length=32, unique=True)),
                ('subject', models.CharField(max_length=512)),
                ('status', models.CharField(blank=True, default='', max_length=64)),
                ('priority', models.CharField(blank=True, default='', max_length=64)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('assigned_to_sf_id', models.CharField(blank=True, default='', max_length=32)),
                ('assigned_to_name', models.CharField(blank=True, default='', max_length=255)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='salesforce_sync.salesforceaccount')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='salesforce_sync.salesforceproject')),
            ],
            options={
                'ordering': ['due_date', 'subject'],
            },
        ),
        migrations.CreateModel(
            name='SalesforceTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sf_id', models.CharField(max_length=32, unique=True)),
                ('sf_user_id', models.CharField(blank=True, default='', max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('role', models.CharField(blank=True, default='', max_length=128)),
                ('local_member_id', models.IntegerField(blank=True, null=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='salesforce_sync.salesforceproject')),
            ],
        ),
        migrations.CreateModel(
            name='SalesforceTimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sf_id', models.CharField(blank=True, default='', max_length=32)),
                ('date', models.DateField()),
                ('duration_minutes', models.IntegerField()),
                ('description', models.TextField(blank=True, default='')),
                ('synced_to_sf', models.BooleanField(default=False)),
                ('sync_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salesforce_sync.salesforceproject')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salesforce_sync.salesforcetask')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
